import {ExtendedTable} from "../index";
import {Template} from "aws-cdk-lib/assertions";
import {AttributeType, BillingMode} from "aws-cdk-lib/aws-dynamodb";
import {ResourceType, TestHelper} from "../../test-helper";

test('Create Table', () => {
  const stack = TestHelper.stack();
  const table = new ExtendedTable(stack, "TestTable", {
    partitionKey: {
      name: "Pk", type: AttributeType.STRING
    },
    sortKey: {
      name: "Sk", type: AttributeType.STRING
    },
    billingMode: BillingMode.PAY_PER_REQUEST
  });
  table.addGlobalSecondaryIndex({
    indexName: "TestIndex",
    partitionKey: {
      name: "Pk",
      type: AttributeType.STRING
    },
    sortKey: {
      name: "Gsi", type: AttributeType.STRING
    },
  });
  const template = Template.fromStack(stack);
  template.resourceCountIs(ResourceType.DYNAMODB_TABLE, 1);
  template.resourceCountIs(ResourceType.CLOUDWATCH_ALARM, 3); // three alarms are generated by default
});
