{
 "title": "YL Service Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "targetGroup",
    "label": "Service Name",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Services Infra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "5xx Errors by Service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/common-private-cdk-1/7f0a72263216769c",
      "TargetGroup": "$targetGroup"
     },
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Unhealthy Hosts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/common-private-cdk-1/7f0a72263216769c",
      "TargetGroup": "$targetGroup"
     },
     "metricName": "UnHealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Throughput by Service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/common-private-cdk-1/7f0a72263216769c",
      "TargetGroup": "$targetGroup"
     },
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Response Time by Service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/common-private-cdk-1/7f0a72263216769c",
      "TargetGroup": "$targetGroup"
     },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Target Group Latency Max & 95 Percentile",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/common-private-cdk-1/7f0a72263216769c",
      "TargetGroup": "targetgroup/payment-otel-test/6fa9549f452b1f3b"
     },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": {
      "LoadBalancer": "app/common-private-cdk-1/7f0a72263216769c",
      "TargetGroup": "$targetGroup"
     },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "p95.00"
    }
   ]
  },
  {
   "title": "Payments Throughput & Success Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }
  },
  {
   "title": "Payment Methods Added",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(increase(adot_payment_event_per_request_total{service_name=\"payment-test\", paymentAction=\"Add\"}[8h] offset 1w))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Payment Microservice Response Time By Action",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "avg(rate(adot_payment_event_per_request_total{service_name=\"payment-test\"}[5m])) by (paymentAction) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Payment Success VS Failure on post",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(increase(adot_payment_event_per_request_total{service_name=\"payment-test\", method=\"POST\", paymentSuccessFailure=\"Success\"}[1h]))\n\n",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(increase(adot_payment_event_per_request_total{service_name=\"payment-test\", method=\"POST\", paymentSuccessFailure!=\"Success\"}[1h]))\n\n",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Payment Microservice Response Time Vs. Last Week",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "\navg(rate(adot_http_server_request_duration_seconds_sum{service_name=\"payment-test\"}[5m])) * 1000\n",
     "legendFormat": "Current Data"
    },
    {
     "expr": "avg(rate(adot_http_server_request_duration_seconds_sum{service_name=\"payment-test\"}[5m] offset 1w)) * 1000",
     "legendFormat": "1 Week Ago"
    }
   ]
  },
  {
   "title": "Payment Microservice - Resident Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "label_replace(quantile_over_time(0.95, adot_process_memory_usage_bytes{service_name=\"payment-test\"}[1h]), \"instance_id\", \"$1\", \"instance\", \"(.*)\")\n",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Payment Microservice Throughput Vs. Last Week",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "\nrate(adot_http_server_request_duration_seconds_count{service_name=\"payment-test\"}[5m])\n",
     "legendFormat": "This Week"
    },
    {
     "expr": "rate(adot_http_server_request_duration_seconds_count{service_name=\"payment-test\"}[5m] offset 1w)",
     "legendFormat": "Last Week"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "sum(rate(adot_http_server_request_duration_seconds_sum{service_name=\"payment-test\"}[5m])) by (http_route)\n/\nsum(rate(adot_http_server_request_duration_seconds_count{service_name=\"payment-test\"}[5m])) by (http_route)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}