import {Template} from 'aws-cdk-lib/assertions';
import {AttributeType, Billing} from 'aws-cdk-lib/aws-dynamodb';
import {ResourceType, HelperTest} from '../../helper.test';
import {ExtendedTableV2} from './extended-table-v2';

test('Create TableV2', () => {
  const stack = HelperTest.stack();
  const table = new ExtendedTableV2(stack, 'TestTable', {
    partitionKey: {
      name: 'Pk',
      type: AttributeType.STRING,
    },
    sortKey: {
      name: 'Sk',
      type: AttributeType.STRING,
    },
    billing: Billing.onDemand(),
  });
  table.addGlobalSecondaryIndex({
    indexName: 'TestIndex',
    partitionKey: {
      name: 'Pk',
      type: AttributeType.STRING,
    },
    sortKey: {
      name: 'Gsi',
      type: AttributeType.STRING,
    },
  });
  const template = Template.fromStack(stack);
  template.resourceCountIs(ResourceType.DYNAMODB_GLOBAL_TABLE, 1);
  template.resourceCountIs(ResourceType.CLOUDWATCH_ALARM, 3); // three alarms are generated by default
});
